import type { AnswerBook } from './types'

// THE SHELF - preview editions carrying FULL original answers written in the
// public style of WolfSpirit99 (direct answer first, story underneath, dry wit).
// They are NOT verbatim Quora posts. Architecture: every slot maps 1:1 to a
// real Quora answer via data/answers.json once Matt's export lands (see
// app/scripts/import-answers-README.md). Source links point at his profile
// until each individual answer URL is confirmed from the export.
export const ANSWER_TOMES: (AnswerBook & { answer: string[]; date?: string; views?: string; reads?: string })[] = [
  {
    id: 'silence-after',
    title: ['THE', 'SILENCE', 'AFTER'],
    theme: 'linear-gradient(150deg,#3a2a18 0%,#20160c 100%)',
    cover: './covers-titled/book-01.jpg',
    topic: 'Family',
    questionSummary: 'What is the hardest part of being a parent that nobody warns you about?',
    takeaway: 'You raise them to leave - and the hardest part starts when they do.',
    pages: 22,
    date: 'March 2021',
    views: '2.4M',
    reads: '11 min',
    answer: [
      'Nobody warns you about the silence. Not the noisy silence of a newborn at 3 a.m., which is really just noise wearing a disguise. I mean the real one - the one that moves into the house around week three of an empty nest.',
      'For eighteen years you organize your whole nervous system around another person. You know what their footsteps sound like from two rooms away. You know the difference between the fridge closing and the front door closing, and you could identify either one blindfolded, mid-dream.',
      'Then one October morning the house stops making those sounds, and you discover that you were never listening to the sounds at all. You were listening to what they meant.',
      'People will tell you to be ready for the tantrums, the teenager, the tuition. Nobody tells you that you are raising the only guests who were always going to leave, and that doing it well makes the leaving hurt more, not less. The better the childhood, the quieter the hallway.',
      'So here is the answer, plain: the hardest part is that you succeed yourself out of a job. And the only comfort I can offer is the one that turned out to be true - the silence is not empty. It is full of everything you said correctly.',
    ],
  },
  {
    id: 'forty-one',
    title: ['FORTY-ONE'],
    theme: 'linear-gradient(150deg,#c46828 0%,#7a3a14 100%)',
    cover: './covers-titled/book-02.jpg',
    topic: 'Work & Starting Over',
    questionSummary: 'Is it ever too late to change careers?',
    takeaway: 'No - but the toll rises every year you leave the road forked.',
    pages: 18,
    date: 'January 2020',
    views: '810K',
    reads: '9 min',
    answer: [
      'No. But I will not lie to you about the price, because the motivational posters do, and you deserve better than posters.',
      'I changed paths at forty-one. The math felt impossible right up until the month I wrote two columns on a legal pad: what staying costs, and what leaving costs. The staying column was longer. It was not even close. It just charged me in a currency I had learned to stop noticing - Sunday evenings, mostly.',
      'Here is what nobody tells you about starting over mid-life: you are not starting from zero. You are starting from experience, which is worth more and markets worse. Your first year will feel like a demotion. Your second will feel like a cheat code, because you will bring judgment to a table full of people who only have energy.',
      'The toll goes up every year you leave the road forked. Regret compounds faster than money does. Pick the bill you can actually live with, and start paying it this week - not Monday, not after the holidays. This week.',
    ],
  },
  {
    id: 'what-the-mistake-knew',
    title: ['WHAT THE', 'MISTAKE', 'KNEW'],
    theme: 'linear-gradient(150deg,#1a0a10 0%,#301218 100%)',
    cover: './covers-titled/book-03.jpg',
    topic: 'Failure',
    questionSummary: 'How do you forgive yourself for a mistake that changed everything?',
    takeaway: 'Your worst error is the only teacher that grades you honestly.',
    pages: 26,
    date: 'July 2021',
    views: '1.1M',
    reads: '12 min',
    answer: [
      'You do not forgive yourself all at once. That is the first true thing, so start there. Forgiveness for the big ones arrives in installments, like a debt you pay down on weird Tuesdays when you suddenly realize a memory has stopped hurting.',
      'The mistake I carry changed the map of my life. For a long time I treated it like a wound - something to keep covered, never look at, never mention. That is the part that nearly ruined me, by the way. Not the mistake. The hiding.',
      'Guilt is useful; it means your conscience has a pulse. Shame is just guilt wearing a heavier coat, and it has never fixed anything. The move is to tell the truth about what you did to exactly one safe person, out loud, in complete sentences. What can still be repaired, repair. What cannot, carry lighter.',
      'Your worst mistake is the only teacher that grades you honestly. Flunk the lesson twice and the third try usually sticks. Mine still visits sometimes. These days it sits politely, like an old instructor checking whether I kept the notes.',
    ],
  },
  {
    id: 'long-goodbye-letters',
    title: ['THE LONG', 'GOODBYE', 'LETTERS'],
    theme: 'linear-gradient(150deg,#161618 0%,#2a2a2e 100%)',
    cover: './covers-titled/book-04.jpg',
    topic: 'Loss',
    questionSummary: 'What do you say to someone who is dying?',
    takeaway: 'Less than you think. Presence beats prose.',
    pages: 14,
    date: 'November 2022',
    views: '3.2M',
    reads: '7 min',
    answer: [
      'Say less than you think you need to. That is the answer, and I will spend the rest of this telling you why, because the person who asked me this years ago deserved more than four words, and so do you.',
      'At the worst goodbye of my life I ran out of language around Thursday. What came after was not speech. It was bad coffee, a blanket, sitting where the light was good, and laughing once - genuinely, awfully - at something small. It was the right thing. Nobody in that room needed eloquence. They needed a witness.',
      'Grief is not a wave you ride; that metaphor sells you a false mercy. Waves end. Grief is a language. You are illiterate at first, then you learn a word a week, and one day, years on, you catch yourself translating for somebody else - and that is how you know you became fluent.',
      'So: sit down. Hold on. Speak plain. The dying are not looking for your best material. They are looking for your company, which is the one thing you cannot draft in advance.',
    ],
  },
  {
    id: 'cheap-coffee-rich-mornings',
    title: ['CHEAP COFFEE,', 'RICH', 'MORNINGS'],
    theme: 'linear-gradient(150deg,#e8645a 0%,#a03a30 100%)',
    cover: './covers-titled/book-05.jpg',
    topic: 'Money & Contentment',
    questionSummary: 'How much money is enough to be happy?',
    takeaway: 'Wealth is the gap between what you want and what you have. Widen it from both ends.',
    pages: 28,
    date: 'May 2020',
    views: '1.9M',
    reads: '10 min',
    answer: [
      'Enough is not a number. It is a gap - the distance between what you want and what you already have. You can widen it from both ends, and here is the part the personal-finance industry will never print: the second lever is free and works today.',
      'The poorest I ever felt was not my lowest balance. It was the month I kept measuring my ordinary Tuesdays against strangers\u2019 highlight reels. Nothing in my bank account had changed. The gap had. That is the whole mechanism of feeling broke while earning well.',
      'Buy the coffee you actually drink. I mean that almost literally - the small daily thing you genuinely savor is worth ten of the status purchases you buy to be seen holding. Audit for the difference. Most people discover a third of their spending is theater.',
      'And save, yes - but save toward a picture, not away from a fear. Fear savings get raided. Picture savings grow. Mine was a porch that does not exist yet. It is amazing how little porch a person actually needs once the picture is specific.',
    ],
  },
  {
    id: 'the-neighbor-principle',
    title: ['THE NEIGHBOR', 'PRINCIPLE'],
    theme: 'linear-gradient(150deg,#6a7a50 0%,#425232 100%)',
    cover: './covers-titled/book-06.jpg',
    topic: 'Community',
    questionSummary: 'How do you actually get to know your neighbors?',
    takeaway: 'A street becomes a home the day someone borrows a ladder and returns soup.',
    pages: 20,
    date: 'August 2019',
    views: '640K',
    reads: '8 min',
    answer: [
      'A street becomes a home the day somebody borrows a ladder and returns it with soup. I have watched this law work on three different streets, in two states, and I am convinced it would hold on a submarine.',
      'The mistake everyone makes is waiting to be invited. Communities do not send invitations; they send weather. You have to be the first useful person, and you have to be specific about it. Not \u201clearge me know if you need anything\u201d - that is a greeting card. \u201cI have a ladder.\u201d \u201cI own a snow blower and I am up at six.\u201d Those are communities, waiting to happen.',
      'Learn one name a week. That is the entire program. A street where four people know each other\u2019s dogs is a street where somebody calls the hospital when a door stays shut too long.',
      'And accept help when it is offered, even when you do not need it. Refusing the casserole refuses the relationship. The soup comes back around. It always comes back around.',
    ],
  },
  {
    id: 'borrowed-courage',
    title: ['BORROWED', 'COURAGE'],
    theme: 'linear-gradient(150deg,#e85a10 0%,#9c4208 100%)',
    cover: './covers-titled/book-07.jpg',
    topic: 'Fear & Change',
    questionSummary: 'How do you find the courage to make a big life change?',
    takeaway: 'Bravery is rented, never owned - you renew it every morning.',
    pages: 24,
    date: 'February 2021',
    views: '1.4M',
    reads: '11 min',
    answer: [
      'You do not find courage. You rent it, nightly, the way you would a tuxedo - and every morning you hand it back, wrinkled, whether you used it or not. This is the whole truth of it, and it is strangely comforting once it lands: nobody owns bravery. Not the soldiers, not the founders, not the people in the documentaries.',
      'The night before my biggest leap I did not feel brave. I felt like a man on a diving board doing arithmetic. What got me off the board was smaller than courage: two lists. What happens if this fails. What happens if I stay. The first list turned out to be survivable. The second list was not.',
      'Fear will tell you the plan has to be complete before you move. Fear is a bad project manager. The move needs to be next-sized, not final-sized - one email, one savings transfer, one phone call made before you feel ready, which you never will.',
      'Rent the courage every morning. Return it tired every night. Do that for a month and you will look back and see the thing fear promised would require a leap was actually a staircase taken one ordinary step at a time.',
    ],
  },
  {
    id: 'table-of-strangers',
    title: ['A TABLE OF', 'STRANGERS'],
    theme: 'linear-gradient(150deg,#1a1e24 0%,#2a3038 100%)',
    cover: './covers-titled/book-08.jpg',
    topic: 'Kindness',
    questionSummary: 'What is one small habit that changed your life?',
    takeaway: 'One extra chair has ended more loneliness than a thousand good intentions.',
    pages: 30,
    date: 'December 2020',
    views: '2.7M',
    reads: '13 min',
    answer: [
      'One extra chair. That is the habit. It has ended more loneliness than a thousand good intentions, and it costs less than the dessert most people skip.',
      'Years ago we started setting the table for one more than we were - literally at first, then in practice. The new coworker who eats lunch alone. The neighbor whose spouse traveled constantly. The kid from down the block who was clearly rehearsing adulthood in a kitchen that had gone quiet. They did not need a program. They needed a Tuesday.',
      'Here is what surprised me: the chair changed us more than it changed them. A household that expects a stranger learns to tell better stories, argue more gently, and notice who is missing. Generosity is a discipline of attention before it is anything else.',
      'You do not need a nonprofit, a platform, or permission. You need a name, a time, and one more place at the table. Small and repeated beats grand and once - in kindness, in savings, in everything I have ever seen actually work.',
    ],
  },
  {
    id: 'the-last-ordinary-day',
    title: ['THE LAST', 'ORDINARY', 'DAY'],
    theme: 'linear-gradient(150deg,#0e1a30 0%,#1a2a48 100%)',
    cover: './covers-titled/book-09.jpg',
    topic: 'Gratitude',
    questionSummary: 'What is something you only appreciated after it was gone?',
    takeaway: 'You never know the last ordinary day until it has been gone a long while.',
    pages: 19,
    date: 'June 2022',
    views: '2.2M',
    reads: '9 min',
    answer: [
      'An average Wednesday. That is my answer, and I would bet a fair amount it is yours too, or will be.',
      'Nobody photographs an ordinary day. The dishes in the sink, the second-hand noise of family in other rooms, the commute you had memorized to the pothole, the voice on the other end of the call you took while half-watching television. There is no album for it. Then it goes - slowly, or all at once - and you would trade a cabinet of holidays for one more unremarkable weeknight.',
      'I am not going to tell you to be grateful, in the way posters tell you to be grateful. I am going to tell you to take inventory. Once a week, look around your average Wednesday like an accountant who suspects the books are about to change: the water is clean, the people answer, the noise is the good kind. Write down three of those. That is the practice. It is not sentiment. It is audit.',
      'The last ordinary day never announces itself. It just leaves, and takes the notes with it. Keep some notes.',
    ],
  },
  {
    id: 'old-dogs-new-roads',
    title: ['OLD DOGS,', 'NEW ROADS'],
    theme: 'linear-gradient(150deg,#b8a0d0 0%,#7a6898 100%)',
    cover: './covers-titled/book-10.jpg',
    topic: 'Reinvention',
    questionSummary: 'Am I too old to start over?',
    takeaway: 'You are never too old to become a beginner - only too practiced at waiting.',
    pages: 16,
    date: 'September 2023',
    views: '980K',
    reads: '8 min',
    answer: [
      'You are never too old to become a beginner. You are only ever too practiced at waiting. Those are different diagnoses, and the second one is treatable.',
      'At an age I will leave vague, my old dog taught the refresher course. New street, new house, new vet - his entire world repackaged at an age the saying had already written off. Within a week he had mapped the sunbeam schedule of a house he had lived in for eight days. Old dogs do not learn new tricks, the saying goes. The saying has clearly never met an old dog with a reason to.',
      'Beginner is not an age. It is a permit you keep forgetting you hold. The seventy-year-old in the pottery class and the nineteen-year-old in the trade apprenticeship are doing the same brave thing: consenting to be visibly unskilled in public, on the way to a life that fits.',
      'Start embarrassingly small. Stay a beginner longer than your pride prefers. And stop asking whether it is too late - ask instead what your one week of trying would cost. Usually less than the waiting has already charged you.',
    ],
  },
]
