#!/usr/bin/env node
/**
 * import-answers.mjs - The Human Answer
 *
 * Turns Matt's real Quora export into per-answer tomes AND wires each book's
 * "back to the original Quora answer" permalink.
 *
 * Usage:
 *   1. Quora -> Settings -> Privacy -> "Download data" -> wait for email
 *   2. unzip; find posts/questions JSON (e.g. answers.json / posts.json)
 *   3. node scripts/import-answers.mjs ~/Downloads/quora-export/answers.json
 *
 * What it does:
 *   - writes app/src/answersData.ts with ONE TOME PER ANSWER
 *     (question = title, full answer text = the page, real date/views)
 *   - sets sourceUrl to the answer's true quora.com permalink so every
 *     opened book links straight back to that same answer
 *   - preserves the shelf look; covers cycle from covers-titled/
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const file = process.argv[2]
if (!file) { console.error('usage: node import-answers.mjs <quora-export.json>'); process.exit(1) }
const raw = JSON.parse(readFileSync(file, 'utf8'))

// Quora exports vary: accept array or {answers:[...]} with common field spellings
const list = Array.isArray(raw) ? raw : (raw.answers || raw.posts || raw.data || [])
if (!list.length) { console.error('no answers found in', file); process.exit(1) }

const esc = (s) => String(s ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n+/g, '\\n')
const slugTitle = (q) => {
  const words = String(q).replace(/[^a-zA-Z0-9 ]/g, '').toUpperCase().split(/\s+/).filter(Boolean)
  const lines = []
  if (words.length <= 3) return [words.join(' ')]
  const per = Math.ceil(words.length / 3)
  for (let i = 0; i < words.length; i += per) lines.push(words.slice(i, i + per).join(' '))
  return lines.slice(0, 3)
}

const themes = [
  'linear-gradient(150deg,#3a2a18 0%,#20160c 100%)',
  'linear-gradient(150deg,#c46828 0%,#7a3a14 100%)',
  'linear-gradient(150deg,#1a0a10 0%,#301218 100%)',
  'linear-gradient(150deg,#161618 0%,#2a2a2e 100%)',
  'linear-gradient(150deg,#e8645a 0%,#a03a30 100%)',
  'linear-gradient(150deg,#6a7a50 0%,#425232 100%)',
  'linear-gradient(150deg,#e85a10 0%,#9c4208 100%)',
  'linear-gradient(150deg,#1a1e24 0%,#2a3038 100%)',
  'linear-gradient(150deg,#0e1a30 0%,#1a2a48 100%)',
  'linear-gradient(150deg,#b8a0d0 0%,#7a6898 100%)',
]

const tomes = list.map((a, i) => {
  const q = a.question || a.title || a.question_text || 'Untitled question'
  const body = a.answer || a.content || a.text || ''
  const paras = String(body).split(/\n{2,}/).map(esc).filter(Boolean)
  const url = a.url || a.share_link || a.permalink || (a.question_url ? a.question_url : null)
  const date = (a.time || a.date || a.created || '').toString().slice(0, 10)
  const views = a.views && Number(a.views) > 999 ? Math.round(a.views / 1000) + 'K' : (a.views ? String(a.views) : undefined)
  const coverIdx = String(i % 10 + 1).padStart(2, '0')
  return `  {
    id: 'a-${i}',
    title: ${JSON.stringify(slugTitle(q))},
    theme: '${themes[i % themes.length]}',
    cover: './covers-titled/book-${coverIdx}.jpg',
    topic: ${JSON.stringify(a.topic || 'Quora Archive')},
    questionSummary: ${JSON.stringify(String(q))},
    takeaway: ${JSON.stringify(String(paras[0] || '').slice(0, 140))},
    pages: ${14 + (i % 17)},
    sourceUrl: ${url ? JSON.stringify(url) : 'null'},
    date: ${JSON.stringify(date || undefined)},
    views: ${views ? JSON.stringify(views) : 'undefined'},
    reads: ${JSON.stringify(Math.max(4, Math.round(body.split(/\\s+/).length / 200)) + ' min')},
    answer: [${paras.map((p) => `'${p}'`).join(',\n      ')}],
  },`
}).join('\n')

const out = `import type { AnswerBook } from './types'

// AUTO-GENERATED by scripts/import-answers.mjs from Matt's Quora export.
// Every tome hard-links its own answer via sourceUrl. Regenerating is safe.
export const ANSWER_TOMES: (AnswerBook & { answer: string[]; date?: string; views?: string; reads?: string })[] = [
${tomes}
]
`
const here = dirname(fileURLToPath(import.meta.url))
writeFileSync(join(here, '..', 'src', 'answersData.ts'), out)
console.log(\`Wrote \${list.length} tomes (\${list.filter((a) => a.url || a.share_link || a.permalink).length} with direct source URLs) -> app/src/answersData.ts\`)
console.log('Rebuild & deploy: cd app && npm run build && cp -r dist/* .. && git add -A && git commit && git push')
